### ISSUE TITLE
Loading images with infinite duration

### ISSUE THREAD

**Issue by zmartell** [LePips/VLCUI#10]
Hi, 

I am having difficulty loading images for forever duration. I can load images fine with 
viewModel.proxy.playNewMedia(VLCVideoPlayer.Configuration( url: URL(string: "https://cdn.mos.cms.futurecdn.net/AT9Bcvo94cTMGmESvL4JCK.jpg")!))

It only seems to last like a second or so, and then i get a stopped event.

**Comment by zmartell** [comment]
https://forum.videolan.org/viewtopic.php?t=133190

mentions theres some image-duration vlc option.

**Comment by LePips** [comment]
Sorry, this project is simply a wrapper around VLCKit and I won't be taking any issues around its functionality, which this is.

I just simply wouldn't recommend using VLC to use images.
