### ISSUE TITLE
setAudioTrack bug

### ISSUE THREAD

**Issue by nevzatbozkurt** [LePips/VLCUI#11]
hello

setAudioTrack function not working because it triggers the function to change subtitles

Proxy.swift line number 76

plaese replace currentVideoSubTitleIndex with currentAudioTrackIndex

**Comment by LePips** [comment]
Thanks for the catch!

- https://github.com/LePips/VLCUI/commit/da3ff09e7a71549936def4db27231395dafa2fe8

**Comment by nevzatbozkurt** [comment]
You're welcome.
