### ISSUE TITLE
Swipe Up/Down etc

### ISSUE THREAD

**Issue by UnknownCoder807** [LePips/VLCUI#13]
Thanks for making this, it's great.  

One thing I think is missing, and I don't know if you intend to add it or not, is to be able to Swipe Up/Down/Left/Right to display some sort of view. 

For example, Swipe Down to show an information panel about the currently playing video.  fully interactive panel so you can change settings etc.  Just the mechanics to display the panel would be ideal. how it looks down to the developer.  Thanks

**Comment by LePips** [comment]
This project's intention is to just provide the VLC rendering layer to SwiftUI, not any sort of overlay.
