### ISSUE TITLE
Doesn’t open .m3u8 file

### ISSUE THREAD

**Issue by nazar-velkakayev** [LePips/VLCUI#16]
### How we can solve this ?
**here is my file: https://bv-video.belet.me/video/hls/253/master.m3u8**

<img width="710" alt="Screenshot 2023-03-04 at 14 56 57" src="https://user-images.githubusercontent.com/89843408/222897041-8bec5848-1964-4e07-90ed-724e781e4e7c.png">

**Comment by LePips** [comment]
This project is just a wrapper around VLCKit and I cannot provide any help on video playback. 

However, for what its worth, I have been able to play HLS streams with VLCKit.

**Comment by nazar-velkakayev** [comment]
have you tried my link?
