### ISSUE TITLE
Random round Play/Stop button is incredibly ambiguous as to what it does

### ISSUE THREAD

**Issue by ShadowJonathan** [LePips/VLCUI#21]
I've encountered this button on both tvOS and iOS with Swiftfin, and i'm incredibly confused as to what it means.

I assume it means autoplay? If so, please use a more specific icon for it (such as `repeat.circle` and `repeat.circle.fill`), since pressing it doesn't do anything but toggling it, and there's no indication of what it's supposed to do.

**Comment by LePips** [comment]
This project only provides a wrapper around VLCKit. Any UI work comes from this package's clients.

**Comment by ShadowJonathan** [comment]
ah, hmm
