### ISSUE TITLE
Playback state not updating on play/pause

### ISSUE THREAD

**Issue by zmartell** [LePips/VLCUI#5]
Hi, 

Using: tvOSVLCUI example

I can play the videos fine but when i press play/pause it doesnt update viewModel.playerState in OverlayView, the others one like viewModel.position does, but not playerState.

**Comment by LePips** [comment]
I've updated the examples with my recent work.

- https://github.com/LePips/VLCUI/commit/5a52f36b39364d8c3268e85c2c70b21a1cb7c290
